services:
  my_django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  frontend:
    build:
      context: frontend
    ports:
      - "8080:8080"